language: ruby
cache: bundler
bundler_args: --without tools --jobs 3 --retry 3

after_success:
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && bundle exec codeclimate-test-reporter'

matrix:
  fast_finish: true
  include:
    - rvm: 2.5.3
      env: RAILS_VERSION='~> 5.2.0'
    - rvm: 2.5.3
      env: RAILS_VERSION='~> 5.1.0'
    - rvm: 2.5.3
      env: RAILS_VERSION='~> 5.0.0'
    - rvm: 2.4.5
      env: RAILS_VERSION='~> 5.0.0'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 5.0.0'
    - rvm: 2.4.5
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.3.8
      env: RAILS_VERSION='~> 4.2.0'
    - rvm: 2.2.10
      env: RAILS_VERSION='~> 4.2.0'
env:
  global:
    - CODECLIMATE_REPO_TOKEN=86c70d1103da065167764882ffb5d184647e2ade2929005a812bea267672cd7e

