language: ruby
sudo: false
cache: bundler
bundler_args: --without tools
rvm:
  - 2.1
matrix:
  fast_finish: true
env:
  matrix:
    - RAILS_VERSION='~> 4.2.0'
    - RAILS_VERSION='~> 4.1.0'
    - RAILS_VERSION='~> 4.0.0'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6efc69df9417bda7808
    on_success: change
    on_failure: always
    on_start: false
