language: ruby
sudo: false
cache: bundler
bundler_args: --without tools
rvm:
  - 2.1
matrix:
  fast_finish: true
env:
  global:
    - CODECLIMATE_REPO_TOKEN=86c70d1103da065167764882ffb5d184647e2ade2929005a812bea267672cd7e
  matrix:
    - RAILS_VERSION='~> 4.2.0'
    - RAILS_VERSION='~> 4.1.0'
    - RAILS_VERSION='~> 4.0.0'
    - RAILS_VERSION='~> 3.2.0'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6efc69df9417bda7808
    on_success: change
    on_failure: always
    on_start: false
