env:
  global:
    - CC_TEST_REPORTER_ID=86c70d1103da065167764882ffb5d184647e2ade2929005a812bea267672cd7e

language: ruby

cache: bundler
bundler_args: --without tools --jobs 3 --retry 3

matrix:
  fast_finish: true
  include:
    - rvm: 2.7.0
      env: RAILS_VERSION='~> 6.0'
    - rvm: 2.7.0
      env: RAILS_VERSION='~> 5.2'
    - rvm: 2.6.5
      env: RAILS_VERSION='~> 6.0'
    - rvm: 2.6.5
      env: RAILS_VERSION='~> 5.2'
    - rvm: 2.5.7
      env: RAILS_VERSION='~> 6.0'
    - rvm: 2.5.7
      env: RAILS_VERSION='~> 5.2'
    - rvm: 2.4.9
      env: RAILS_VERSION='~> 5.2'
    - rvm: 2.4.9
      env: RAILS_VERSION='~> 4.2'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
